### ISSUE TITLE
panic: runtime error: slice bounds out of range [:775192] with capacity 0

### ISSUE THREAD

**Issue by mattisonchao** [streamnative/oxia#516]
```
{"level":"info","time":"2024-09-15T05:33:54.442984882Z","component":"internal-rpc-server","namespace":"xxxxxx","peer":"127.0.0.6:58591","shard":3,"time":"2024-09-15T05:33:54.442991809Z","message":"Received SendSnapshot request"}
panic: runtime error: slice bounds out of range [:775192] with capacity 0

goroutine 576 [running]:
github.com/streamnative/oxia/server/wal.readInt(...)
	/src/oxia/server/wal/wal_ro_segment.go:43
github.com/streamnative/oxia/server/wal.fileOffset(...)
	/src/oxia/server/wal/wal_ro_segment.go:47
github.com/streamnative/oxia/server/wal.(*readWriteSegment).Read(0xc001717780, 0x2f505)
	/src/oxia/server/wal/wal_rw_segment.go:116 +0x24c
github.com/streamnative/oxia/server/wal.(*wal).readAtIndex(0xc000494140, 0x2f505)
	/src/oxia/server/wal/wal_impl.go:185 +0x28f
github.com/streamnative/oxia/server/wal.(*forwardReader).ReadNext(0xc000cf4280)
	/src/oxia/server/wal/wal_reader.go:94 +0x112
github.com/streamnative/oxia/server/wal.(*trimmer).readAtOffset(0xc000bee840, 0x2f505)
	/src/oxia/server/wal/wal_trimmer.go:200 +0xb6
github.com/streamnative/oxia/server/wal.(*trimmer).doTrim(0xc000bee840)
	/src/oxia/server/wal/wal_trimmer.go:128 +0x205
github.com/streamnative/oxia/server/wal.(*trimmer).run(0xc000bee840)
	/src/oxia/server/wal/wal_trimmer.go:100 +0xb6
github.com/streamnative/oxia/common.DoWithLabels.func1({0x247f668?, 0xc000bd3170?})
	/src/oxia/common/pprof.go:46 +0x13
runtime/pprof.Do({0x247f6a0?, 0xc000da2050?}, {{0xc000ca0f40?, 0xc000654078?, 0xc00031d960?}}, 0xc000956f30)
	/usr/local/go/src/runtime/pprof/runtime.go:51 +0x9d
github.com/streamnative/oxia/common.DoWithLabels({0x247f6a0, 0xc000da2050}, 0xc000943500, 0xc0009c0e40)
	/src/oxia/common/pprof.go:42 +0x356
created by github.com/streamnative/oxia/server/wal.newTrimmer in goroutine 574
	/src/oxia/server/wal/wal_trimmer.go:63 +0x53b
```

**Comment by mattisonchao** [comment]
This issue should caused by corrupted data. we will introduce CRC for that.

**Comment by mattisonchao** [comment]
fixed by https://github.com/streamnative/oxia/pull/538
