### ISSUE TITLE
flaky-test: TestWalTrimUpToCommitOffset

### ISSUE THREAD

**Issue by mattisonchao** [streamnative/oxia#580]
```
panic: test timed out after 10m0s
	running tests:
		TestWalTrimUpToCommitOffset (10m0s)
		TestWalTrimUpToCommitOffset/test-70 (9m58s)

goroutine 378 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:2373 +0x265
created by time.goFunc
	/opt/hostedtoolcache/go/1.23.3/x64/src/time/sleep.go:[215](https://github.com/streamnative/oxia/actions/runs/11866692701/job/33073940897?pr=579#step:9:216) +0x45

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00010c680, {0x10f3c22, 0x1b}, 0x1133d38)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1751 +0x851
testing.runTests.func1(0xc00010c680)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:[216](https://github.com/streamnative/oxia/actions/runs/11866692701/job/33073940897?pr=579#step:9:217)8 +0x86
testing.tRunner(0xc00010c680, 0xc0001e9ae0)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1690 +0x227
testing.runTests(0xc000110480, {0x17bf340, 0x23, 0x23}, {0x7f9b2dac3a68?, 0x40?, 0x17ccc80?})
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:2166 +0x8bf
testing.(*M).Run(0xc0003401e0)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:2034 +0xf18
main.main()
	_testmain.go:129 +0x165

goroutine 90 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000382340, {0xc0004cdc99, 0x7}, 0x1133ea8)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1751 +0x851
github.com/streamnative/oxia/server/wal.TestWalTrimUpToCommitOffset(0xc000382340)
	/home/runner/work/oxia/oxia/server/wal/wal_trimmer_test.go:98 +0x93
testing.tRunner(0xc000382340, 0x1133d38)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1743 +0x826

goroutine 386 [chan receive, 9 minutes]:
github.com/streamnative/oxia/server/wal.(*trimmer).Close(0xc000601680)
	/home/runner/work/oxia/oxia/server/wal/wal_trimmer.go:96 +0x158
github.com/streamnative/oxia/server/wal.(*wal).closeWithoutLock(0xc0001b46e0)
	/home/runner/work/oxia/oxia/server/wal/wal_impl.go:242 +0x199
github.com/streamnative/oxia/server/wal.(*wal).Close(0xc0001b46e0)
	/home/runner/work/oxia/oxia/server/wal/wal_impl.go:230 +0xe5
github.com/streamnative/oxia/server/wal.TestWalTrimUpToCommitOffset.func1(0xc000194000)
	/home/runner/work/oxia/oxia/server/wal/wal_trimmer_test.go:158 +0x6a6
testing.tRunner(0xc000194000, 0x1133ea8)
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 90
	/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1743 +0x826

goroutine 387 [sync.RWMutex.RLock, 9 minutes]:
sync.runtime_SemacquireRWMutexR(0xc0001b46f0?, 0x1?, 0x272d9ec?)
	/opt/hostedtoolcache/go/1.23.3/x64/src/runtime/sema.go:100 +0x25
sync.(*RWMutex).RLock(0xc0001b46e0)
	/opt/hostedtoolcache/go/1.23.3/x64/src/sync/rwmutex.go:72 +0x65
github.com/streamnative/oxia/server/wal.(*wal).readAtIndex(0xc0001b46e0, 0x57)
	/home/runner/work/oxia/oxia/server/wal/wal_impl.go:166 +0xb6
github.com/streamnative/oxia/server/wal.(*forwardReader).ReadNext(0xc00013e440)
	/home/runner/work/oxia/oxia/server/wal/wal_reader.go:94 +0x2a6
github.com/streamnative/oxia/server/wal.(*trimmer).readAtOffset(0xc000601680, 0x57)
	/home/runner/work/oxia/oxia/server/wal/wal_trimmer.go:205 +0xf0
github.com/streamnative/oxia/server/wal.(*trimmer).doTrim(0xc000601680)
	/home/runner/work/oxia/oxia/server/wal/wal_trimmer.go:133 +0x515
github.com/streamnative/oxia/server/wal.(*trimmer).run(0xc000601680)
	/home/runner/work/oxia/oxia/server/wal/wal_trimmer.go:105 +0x1a7
github.com/streamnative/oxia/common.DoWithLabels.func1({0x1[220](https://github.com/streamnative/oxia/actions/runs/11866692701/job/33073940897?pr=579#step:9:221)a40?, 0xc000174330?})
	/home/runner/work/oxia/oxia/common/pprof.go:46 +0x2f
runtime/pprof.Do({0x1220a78, 0xc000036460}, {{0xc000393ac0?, 0x35?, 0x4bc0f6?}}, 0xc000082f10)
	/opt/hostedtoolcache/go/1.23.3/x64/src/runtime/pprof/runtime.go:51 +0x118
github.com/streamnative/oxia/common.DoWithLabels({0x1220a78, 0xc000036460}, 0xc0004d9350, 0xc000280930)
	/home/runner/work/oxia/oxia/common/pprof.go:42 +0x585
created by github.com/streamnative/oxia/server/wal.newTrimmer in goroutine 386
	/home/runner/work/oxia/oxia/server/wal/wal_trimmer.go:63 +0x8f9
FAIL	github.com/streamnative/oxia/server/wal	600.050s
```

**Comment by lsytj0413** [comment]
reproduced at https://github.com/streamnative/oxia/actions/runs/13535939433/job/37827547221?pr=627

```
Feb 26 03:35:28.888758 WRN The segment index file is corrupted and the index is being rebuilt. path=/tmp/TestRO_auto_recover_broken_index1197743193/001/0.idxx
Feb 26 03:35:28.888986 INF The segment index file has been rebuilt. path=/tmp/TestRO_auto_recover_broken_index1197743193/001/0.idxx
Feb 26 03:35:30.044229 WRN discard the corrupted uncommitted data. error={"error":"expected payload size: 10000011. actual buf size: 1024 : oxia: offset out of bounds","kind":"*errors.withStack","stack":null} entryId=2
Feb 26 03:35:30.048182 WRN discard the corrupted uncommitted data. error={"error":" expected crc: 927971403; actual crc: 1235739491: oxia: data corrupted","kind":"*errors.withStack","stack":null} entryId=2
Feb 26 03:35:30.517868 INF checking... first-offset=3
Feb 26 03:35:30.529173 INF checking... first-offset=87
Feb 26 03:35:30.[54](https://github.com/streamnative/oxia/actions/runs/13535939433/job/37827547221?pr=627#step:10:55)5991 INF checking... first-offset=2
Feb 26 03:35:30.557555 INF checking... first-offset=87
Feb 26 03:35:30.573996 INF checking... first-offset=2
Feb 26 03:35:30.58[55](https://github.com/streamnative/oxia/actions/runs/13535939433/job/37827547221?pr=627#step:10:56)45 INF checking... first-offset=87
Feb 26 03:35:30.601304 INF checking... first-offset=2
Feb 26 03:35:30.612889 INF checking... first-offset=87
Feb 26 03:35:30.630295 INF checking... first-offset=2
Feb 26 03:35:30.641920 INF checking... first-offset=87
Feb 26 03:35:30.657596 INF checking... first-offset=2
Feb 26 03:35:30.669160 INF checking... first-offset=87
Feb 26 03:35:30.688393 INF checking... first-offset=2
Feb 26 03:35:30.699999 INF checking... first-offset=87
Feb 26 03:35:30.715501 INF checking... first-offset=2
Feb 26 03:35:30.727081 INF checking... first-offset=87
Feb 26 03:35:30.743294 INF checking... first-offset=2
Feb 26 03:35:30.754870 INF checking... first-offset=87
Feb 26 03:35:30.770850 INF checking... first-offset=2
Feb 26 03:35:30.782418 INF checking... first-offset=87
Feb 26 03:35:30.799073 INF checking... first-offset=2
Feb 26 03:35:30.810703 INF checking... first-offset=87
Feb 26 03:35:30.827177 INF checking... first-offset=2
Feb 26 03:35:30.838776 INF checking... first-offset=87
Feb 26 03:35:30.854602 INF checking... first-offset=2
Feb 26 03:35:30.866149 INF checking... first-offset=87
Feb 26 03:35:30.881[56](https://github.com/streamnative/oxia/actions/runs/13535939433/job/37827547221?pr=627#step:10:57)4 INF checking... first-offset=2
Feb 26 03:35:30.893113 INF checking... first-offset=87
Feb 26 03:35:30.908071 INF checking... first-offset=2
Feb 26 03:35:30.919607 INF checking... first-offset=87
Feb 26 03:35:30.934612 INF checking... first-offset=2
Feb 26 03:35:30.946144 INF checking... first-offset=87
Feb 26 03:35:30.961935 INF checking... first-offset=2
Feb 26 03:35:30.973463 INF checking... first-offset=87
Feb 26 03:35:30.989162 INF checking... first-offset=2
Feb 26 03:35:31.000688 INF checking... first-offset=87
Feb 26 03:35:31.016816 INF checking... first-offset=2
Feb 26 03:35:31.028370 INF checking... first-offset=87
Feb 26 03:35:31.043680 INF checking... first-offset=2
Feb 26 03:35:31.055242 INF checking... first-offset=87
Feb 26 03:35:31.070504 INF checking... first-offset=2
Feb 26 03:35:31.082032 INF checking... first-offset=87
Feb 26 03:35:31.099117 INF checking... first-offset=2
Feb 26 03:35:32.535894 INF checking... first-offset=87
Feb 26 03:35:32.553343 INF checking... first-offset=2
Feb 26 03:35:32.565036 INF checking... first-offset=87
Feb 26 03:35:32.583870 INF checking... first-offset=2
Feb 26 03:35:32.595542 INF checking... first-offset=87
Feb 26 03:35:32.612407 INF checking... first-offset=2
Feb 26 03:35:32.624064 INF checking... first-offset=87
Feb 26 03:35:32.640854 INF checking... first-offset=2
Feb 26 03:35:32.652501 INF checking... first-offset=87
Feb 26 03:35:32.669710 INF checking... first-offset=2
Feb 26 03:35:32.681499 INF checking... first-offset=87
Feb 26 03:35:32.698784 INF checking... first-offset=2
Feb 26 03:35:32.710423 INF checking... first-offset=87
Feb 26 03:35:32.727760 INF checking... first-offset=2
Feb 26 03:35:32.739418 INF checking... first-offset=87
Feb 26 03:35:32.756164 INF checking... first-offset=2
Feb 26 03:35:32.767782 INF checking... first-offset=87
Feb 26 03:35:32.784692 INF checking... first-offset=2
Feb 26 03:35:32.796305 INF checking... first-offset=87
Feb 26 03:35:32.8135[57](https://github.com/streamnative/oxia/actions/runs/13535939433/job/37827547221?pr=627#step:10:58) INF checking... first-offset=2
Feb 26 03:35:32.825172 INF checking... first-offset=87
Feb 26 03:35:32.842126 INF checking... first-offset=2
Feb 26 03:35:32.853730 INF checking... first-offset=87
Feb 26 03:35:32.870713 INF checking... first-offset=2
Feb 26 03:35:32.882315 INF checking... first-offset=87
Feb 26 03:35:32.899408 INF checking... first-offset=2
Feb 26 03:35:32.911024 INF checking... first-offset=87
Feb 26 03:35:32.927726 INF checking... first-offset=2
Feb 26 03:35:32.939345 INF checking... first-offset=87
Feb 26 03:35:32.956141 INF checking... first-offset=2
Feb 26 03:35:32.971[58](https://github.com/streamnative/oxia/actions/runs/13535939433/job/37827547221?pr=627#step:10:59)2 INF checking... first-offset=87
Feb 26 03:35:32.991[59](https://github.com/streamnative/oxia/actions/runs/13535939433/job/37827547221?pr=627#step:10:60)1 INF checking... first-offset=2
Feb 26 03:35:33.003230 INF checking... first-offset=87
Feb 26 03:35:33.021196 INF checking... first-offset=2
Feb 26 03:35:33.033057 INF checking... first-offset=87
Feb 26 03:35:33.093278 INF checking... first-offset=2
Feb 26 03:35:33.104911 INF checking... first-offset=87
Feb 26 03:35:33.125640 INF checking... first-offset=2
Feb 26 03:35:33.137581 INF checking... first-offset=87
Feb 26 03:35:33.159514 INF checking... first-offset=2
Feb 26 03:35:33.171189 INF checking... first-offset=87
Feb 26 03:35:33.188752 INF checking... first-offset=2
Feb 26 03:35:33.200386 INF checking... first-offset=87
Feb 26 03:35:33.217464 INF checking... first-offset=2
Feb 26 03:35:33.229134 INF checking... first-offset=87
Feb 26 03:35:33.252535 INF checking... first-offset=2
Feb 26 03:35:33.264618 INF checking... first-offset=87
Feb 26 03:35:33.285581 INF checking... first-offset=2
Feb 26 03:35:33.297451 INF checking... first-offset=87
Feb 26 03:45:28.937536 ERR Failed to trim the wal error={"error":"failed to read from wal at offset 0 first=0 last=999: failed to open segment txn file /tmp/TestReadOnlySegmentsGroupTrimSegments1[60](https://github.com/streamnative/oxia/actions/runs/13535939433/job/37827547221?pr=627#step:10:61)9322949/001/test/shard-0/0.txnx: open /tmp/TestReadOnlySegmentsGroupTrimSegments1609322949/001/test/shard-0/0.txnx: no such file or directory","kind":"*errors.withStack","stack":null} component=wal-trimmer namespace=test shard=0
coverage: 77.1% of statements
panic: test timed out after 10m0s
	running tests:
		TestWalTrimUpToCommitOffset (9m58s)
		TestWalTrimUpToCommitOffset/test-94 (9m56s)
```
